- hosts: all

  tasks:
    - ping: ~

    - name: Update APT package manager repositories cache
        become: yes
        become_method: su
        become_user: mach3
        become_flags: -K
        apt:
        update_cache: yes

    - name: Upgrade installed packages
      apt:
        upgrade: dist
...
