- hosts: all

  tasks:
    - ping: ~

    - name: Update APT package manager repositories cache
      become: false
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      become: false
      apt:
        upgrade: dist
...
