'''
- hosts: all
    become: true
    become_method: su
    become_user: mach3
    become_flags: '-s /bin/sh -K'

  tasks:
    - ping: ~

    - name: Update APT package manager repositories cache
        apt:
        update_cache: yes

    - name: Upgrade installed packages
        apt:
        upgrade: dist
...
